// This Is Sem API

const Sems = [{
    id:"s1",
    title:"Semester-1",
    description:"To know more about this semester.Click the button 'Semester Details'.",
    image:require("../assets/1st.jpg"),
    syllabus:"Click me for Syllabus",
    subtit:"List Of Subjects: ",
    subject1:"1.Fundamentals Of Computer And Introduction To Programming",
    subject2:"2.Finite Automata and Formal Languages",
    subject3:"3.Microprocessors",
    subject4:"4.Computer Organization",
    subject5:"5.Java Programming Lab",  
},
{
    id:"s2", 
    title:"Semester-2",
    description:"To know more about this semester.Click the button 'Semester Details'.",
    image:require("../assets/2nd.gif"),
    syllabus:"Click me for Syllabus",
    subtit:"List Of Subjects in Semester 2 : ",
    subject1:"1.Programming for Problem solving",
    subject2:"2.Finite Automata and Formal Languages",
    subject3:"3.Microprocessors",
    subject4:"4.Computer Organization",
    subject5:"5.Java Programming Lab",
    
},
{
    id:"s3",
    title:"Semester-3",
    description:"To know more about this semester.Click the button 'Semester Details'.",
    image:require("../assets/3rd.gif"),
    syllabus:"Click me for Syllabus",
    subtit:"List Of Subjects : ",
    subject1:"1.Logic Design",
    subject2:"2.Data Structures with C",
    subject3:"3.OOP with C++",
    subject4:"4.Fundamentals Of Cyber Security",
    subject5:"5.Fundamentals Of IOT",
    
    
},
{
    id:"s4",
    title:"Semester-4",
    description:"To know more about this semester.Click the button 'Semester Details'.",
    image:require("../assets/4.gif"),
    syllabus:"Click me for Syllabus",
    subtit:"List Of Subjects : ",
    subject1:"1.Computer Based Numerical And Statistical Technique",
    subject2:"2.Finite Automata and Formal Languages",
    subject3:"3.Microprocessors",
    subject4:"4.Computer Organization",
    subject5:"5.Java Programming Lab",
    
},
{
    id:"s5",
    title:"Semester-5",
    description:"To know more about this semester.Click the button 'Semester Details'.",
    image:require("../assets/5.jpg"),
    syllabus:"Click me for Syllabus",
    subtit:"List Of Subjects : ",
    subject1:"1.System Software",
    subject2:"2.Operating Systems",
    subject3:"3.Database Management System",
    subject4:"4.Design Analysis And Algorithm",
    subject5:"5.Career Skills",
    
},
{
    id:"s6",
    title:"Semester-6",
    description:"To know more about this semester.Click the button 'Semester Details'.",
    image:require("../assets/6.png"),
    syllabus:"Click me for Syllabus",
    subtit:"List Of Subjects : ",
    subject1:"1.Compiler Design",
    subject2:"2.Computer Networks",
    subject3:"3.Software Engineering",
    subject4:"4.Full Stack Web Development",
    subject5:"5.Career Skills",
    
},
{
    id:"s7",
    title:"Semester-7",
    description:"To know more about this semester.Click the button 'Semester Details'.",
    image:require("../assets/7.jpg"),
    syllabus:"Click me for Syllabus",
    subtit:"List Of Subjects : ",
    subject1:"1.Cryptography",
    subject2:"2.Computer Networks-II",
    subject3:"3.Advanced Computer Architecture",
    subject4:"4.Artificial Intelligence",
    subject5:"5.Software Verification and Validation and Testing",
    
},
{
    id:"s8",
    title:"Semester-8",
    description:"To know more about this semester.Click the button 'Semester Details'.",
    image:require("../assets/8.jpg"),
    syllabus:"Click me for Syllabus",
    subtit:"List Of Subjects : ",
    subject1:"1.Mobile Computing",
    subject2:"2.Disaster Managment",
    subject3:"3.Soft Computing",
    subject4:"4.Mobile Application Development",
    subject5:"5.Computer Graphics",
},
]

export default Sems;

